---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/pages
  label: Pages
  create: documents
  match: "**/*"
- type: directory
  path: content/open-positions
  label: Open positions
  create: documents
  match: "**/*"
  templates:
  - open-position
- type: directory
  path: content/employees
  label: Employees
  create: documents
  match: "**/*"
  templates:
  - employee
- type: directory
  path: content/posts
  label: Posts
  create: all
  match: "**/*"
- type: directory
  path: content/case
  label: Case
  create: documents
  match: "**/*"
  templates:
  - case
upload_dir: content/media/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: 
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  instant_preview_command: gatsby develop -H 0.0.0.0 -p 8080
  publish_command: gatsby build
  output_directory: public
  preview_command: gatsby build
